Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/10/2024
Var
// Seção de Declarações das variáveis 
base: inteiro
finals: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
base <- 100
enquanto (base < 110) faca
base<-base + 1
escreval(base)
fimenquanto

Fimalgoritmo